lerna.json

Update labels
Use internal label in this PR

internal: lerna labels

---

package.json
packages/patternfly-4/react-styles/README.md
packages/react-icons/src/createIcon.js

fix(release): test releases with readme and icon updates

---

.travis/after_success.sh

fix(pro): add pro option to deploy-once

---

package.json
packages/patternfly-4/react-core/README.md

fix(pkgs): attempt to release only sub packages

---

lerna.json
package.json
packages/patternfly-4/react-core/README.md

fix(lerna): remove package workspace

---

lerna.json
package.json

fix(ws): attempt to try different workspace solutions

---

lerna.json
packages/patternfly-4/react-core/README.md

fix(core): add additional ignore to lerna.json

---

.travis/publish_github_release.js
package.json
packages/patternfly-4/package.json
packages/patternfly-4/react-core/README.md

fix(core): add publish script to fix release notes

---

packages/eslint-plugin-patternfly-react/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json

fix(git): update git links

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js

fix(core): tag with label

---

packages/eslint-plugin-patternfly-react/package.json

chore(eslint): start with version 1.0.0

---

packages/patternfly-4/react-core/src/components/Alert/Alert.js

fix(core): 1/2

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js

fix(core): 2/2

---

.releaserc
.travis/after_success.sh
package.json

chore(root): lerna version

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js

fix(core): 3

---

README.md
greenkeeper.json

Add greenkeeper - first pass

---

package.json
yarn.lock

chore(deps): remove a dependency

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js

feat(core): label

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js

fix: change

---

packages/patternfly-4/react-core/src/components/Avatar/Avatar.docs.js
packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js

fix: core and docs

---

package.json
packages/patternfly-4/react-core/src/components/Avatar/Avatar.docs.js

fix: breaking change in core

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js
packages/react-icons/src/common.js

chore: core/icons

---

GETTING-STARTED.md
packages/patternfly-4/react-core/CONTRIBUTING.md

fix: root/core

---

.travis/after_success.sh
package.json
yarn.lock

chore: switch to semantic release

---

GETTING-STARTED.md
packages/patternfly-4/react-core/CONTRIBUTING.md

fix: root/core post semantic-release

---

GETTING-STARTED.md
packages/patternfly-4/react-core/CONTRIBUTING.md

fix: root/core post workspaces

---

packages/patternfly-4/react-core/CONTRIBUTING.md

fix: root/core after subfolder

---

GETTING-STARTED.md
packages/patternfly-4/react-dev-common/.eslintrc.js
packages/patternfly-4/react-docs/gatsby-node.js
packages/patternfly-4/react-styles/testUtils.js
packages/react-icons/README.md

fix: root/docs/styles/icons/dev-common

---

packages/patternfly-4/react-core/CONTRIBUTING.md

fix: debug pr comments

---

packages/patternfly-4/react-core/CONTRIBUTING.md

fix: test pr comment

---

packages/patternfly-4/react-core/CONTRIBUTING.md
packages/patternfly-4/react-dev-common/verifyCoreVersions.js

fix: common/core

---

packages/patternfly-4/react-core/CONTRIBUTING.md
packages/patternfly-4/react-dev-common/package.json
release.config.js

chore: common/core
